spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idp
    username: ${POSTGRES_USERNAME_PROD}
    password: ${POSTGRES_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration